### ISSUE TITLE
远程服务器返回错误：（400）错误的请求

### ISSUE THREAD

**Issue by Nobiel** [tiancaihb/BaiduOldDriver#2]
是服务器又挂了吗

**Comment by ghost** [comment]
这次是我的百度网盘满了 真是丧心病狂啊

**Comment by Nobiel** [comment]
会员空间都撑满了。。。或许可以加个定期自动删除转存到你网盘里的文件的功能？

**Comment by ghost** [comment]
老司机太多，大开眼界。我只是测试一下，所以估计过几天就关了。

**Comment by aldington-david** [comment]
每天12小时清空一次估计差不多

**Comment by aldington-david** [comment]
好吧(∩_∩)原来还有这种好办法，群里合租个SVIP就可以自己用了qwq

**Comment by ghost** [comment]
@228207876 链接有效期是8小时。我不清空是因为想人工从里面找一些我喜欢的资源。
只有开始下载的时候会判断文件是否存在，因此不考虑断点续传的下载方式的话，完全可以比如10分钟之后删。

**Comment by Nobiel** [comment]
@228207876 求哪里有合租

**Comment by aldington-david** [comment]
(⊙o⊙)…毕竟代码今天才看到合租的话要看情况咯，老司机群估计<(￣ˇ￣)/

**Comment by Nobiel** [comment]
@228207876 老司机知道怎样下种子速度会比较快吗，如果没有离线下载的话速度太慢了

**Comment by aldington-david** [comment]
@Nobiel 去各大PT站咯，理论上你上传越多下载越快，或者用迅雷破解版呗

**Comment by Nobiel** [comment]
@228207876 有ipv6的话下PT是挺快的，问题是有时候只能下到BT资源，而且迅雷破解版还能用？

**Comment by aldington-david** [comment]
@Nobiel 还可以用，ipv6环境我不大清楚。

**Comment by wuhen123** [comment]
返回400错误，又翻车了

**Comment by aldington-david** [comment]
我这有能突破10KB的百度云版本，不过估计放出来不出一天就得GG，这估计是最后一个版本了

**Comment by jzmswe** [comment]
多注册几个度盘ID，把你不想删除的发给别的ID，这样原ID空间就出来了，我经常这么干。

**Comment by garydevil** [comment]
又翻车了.....

**Comment by ghost** [comment]
已经决定这部分测试结束了

**Comment by garydevil** [comment]
已经决定这部分测试结束了0 o ohelp

**Comment by LIESEACN** [comment]
伤心 可以合租就好了 我的账号基本都是10kb idm下载

**Comment by Nobiel** [comment]
有合租会员的么 借源码自己搭建一个吧

**Comment by ghost** [comment]
@Nobiel 我觉得服务器的程序还需要改进，主要是崩溃之后重启（用shell的死循环就好，可能比写到程序里更方便？），以及隔一段时间自动清理中转文件夹。
另外，大概在其他不同地方登录10次之后，更早的登录会过期。也应该加上这样的检测，如果发现被踢下线就重新登录。 简单的做法是只要出错就检查一下（有这个函数）

**Comment by Nobiel** [comment]
@tiancaihb 嗯，这块我不大懂，支持改进。
